import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/web/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased max-w-7xl mx-auto w-full px-4 md:px-6 lg:px-8`}
      >
            <Navbar/>
        <main className="mt-10">
        {children}
        </main>

      </body>
    </html>
  );
}
